# $FreeBSD$
# All the dts files for Apple systems we support.

.if ${MACHINE_ARCH} == "aarch64"
DTS=	\
	apple/t8103-j274.dts \
	apple/t8103-j293.dts \
	apple/t8103-j313.dts \
	apple/t8103-j456.dts \
	apple/t8103-j457.dts

.endif

.include <bsd.dtb.mk>
