# $FreeBSD$

freebsd_instance:
   image_family: freebsd-14-0-snap

task:
  install_script:
    - pkg delete -y python2
    - pkg autoremove -y
    - pkg update
    - pkg upgrade -y
    - pkg install -y devel/py-pytest net/scapy
    - make -C libexec/atf/atf-pytest-wrapper -j$(sysctl -n hw.ncpu) all install
    - make -C tests/sys/common -j$(sysctl -n hw.ncpu) all install
    - make -C tests/atf_python -j$(sysctl -n hw.ncpu) all install
    - cp $CIRRUS_WORKING_DIR/tests/conftest.py /usr/tests
  setup_script:
    - cd sys/modules/if_epair
    - make -j$(sysctl -n hw.ncpu)
    - make -j$(sysctl -n hw.ncpu) install
    - mv /boot/modules/if_epair.ko /boot/kernel/if_epair.ko
    - cd $CIRRUS_WORKING_DIR
    - make -C tests/sys/net -j$(sysctl -n hw.ncpu) all install
  test_epair_script:
    - kyua test -k /usr/tests/Kyuafile sys/net/if_epair
  always:
    test_epair_report_script:
      - kyua report --results-file /usr/tests --results-filter failed --verbose
