# $FreeBSD$

freebsd_instance:
  image_family: freebsd-14-0-snap

task:
  timeout_in: 120m
  install_script:
  - pkg install -y net/scapy
  - ls
  - cd sbin/ping
  - make
  - make install
  test_ping_script:
  - kyua test -k /usr/tests/Kyuafile sbin/ping/ping_test
  always:
    test_ping_report_script:
    - cd /usr/tests
    - kyua report --results-file=LATEST --results-filter=failed --verbose
