compute_engine_instance:
  # Image list available via
  # gcloud compute images list --project freebsd-org-cloud-dev --no-standard-images
  platform: freebsd
  image_project: freebsd-org-cloud-dev
  image: freebsd-13-2-release-amd64

task:
  matrix:
  - name: World and kernel amd64 build and boot smoke test
    env:
      TARGET: amd64
      TARGET_ARCH: amd64
      TOOLCHAIN_PKG: llvm15
  - name: World and kernel arm64 build and boot smoke test
    trigger_type: manual
    env:
      TARGET: arm64
      TARGET_ARCH: aarch64
      TOOLCHAIN_PKG: llvm15
  - name: World and kernel gcc12 amd64 build and boot smoke test
    trigger_type: manual
    env:
      TARGET: amd64
      TARGET_ARCH: amd64
      TOOLCHAIN_PKG: amd64-gcc12
  timeout_in: 120m
  install_script:
  - sh .cirrus-ci/pkg-install.sh ${TOOLCHAIN_PKG} git-lite

  xxx_upgrade_pkg_script:
  - fetch http://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/pkg-1.20.9.pkg
  - pkg install -y ./pkg-1.20.9.pkg
  - rm -f pkg-1.20.9.pkg

  setup_script:
  - uname -a
  - gpart show
  - df -m
  - pkg --version
  - pw useradd -n user -m
  - mkdir -p /usr/obj/$(pwd -P)
  - chown user:user /usr/obj/$(pwd -P)
  - su user -c "git config --global --add safe.directory $(pwd -P)"

  build_world_script:
  - su user -c "make -j$(sysctl -n hw.ncpu) ${EXTRA_MAKE_FLAGS} CROSS_TOOLCHAIN=${TOOLCHAIN} WITHOUT_TOOLCHAIN=yes buildworld"

  package_script:
  - su user -c "make CROSS_TOOLCHAIN=${TOOLCHAIN_PKG} WITHOUT_TOOLCHAIN=yes PKG_FORMAT=tar packages"
  package_check_script:
  - su user -c "/usr/libexec/flua tools/pkgbase/metalog_reader.lua -c /usr/obj/$(pwd -P)/${TARGET}.${TARGET_ARCH}/worldstage/METALOG"
  test_script:
  - sh .cirrus-ci/pkg-install.sh qemu-nox11
  - sh tools/boot/ci-qemu-test.sh
  installworld_script:
  - su user -c "make -j$(sysctl -n hw.ncpu) CROSS_TOOLCHAIN=${TOOLCHAIN_PKG} WITHOUT_TOOLCHAIN=yes installworld"
  test_strfmon_script:
  - kyua test -k /usr/tests/Kyuafile lib/libc/stdlib/strfmon_test
  always:
    test_strfmon_report_script:
    - cd /usr/tests
    - kyua report --results-file=LATEST --results-filter=failed --verbose
  post_script:
  - df -m
  - du -m -s /usr/obj
