# $FreeBSD$

freebsd_instance:
   image_family: freebsd-14-0-snap

task:
  install_script:
    - pkg delete -y python2
    - pkg autoremove -y
    - pkg update
    - pkg upgrade -y
    - pkg install -y net/isc-dhcp44-server
    - make -C tests/sys/common -j$(sysctl -n hw.ncpu) all install
  setup_script:
    - make -C sbin/dhclient -j$(sysctl -n hw.ncpu) all install
  test_dhclient_script:
    - kyua test -k /usr/tests/Kyuafile sbin/dhclient/option-domain-search_test
    - kyua test -k /usr/tests/Kyuafile sbin/dhclient/pcp
  always:
    test_dhclient_report_script:
      - cd /usr/tests
      - kyua report --results-file=LATEST --results-filter=failed --verbose
