
freebsd_instance:
   image_family: freebsd-14-0-snap

task:
  install_script:
    - pkg upgrade -y
    - pkg install -y devel/py-pytest net/scapy
  setup_script:
    - make buildkernel
    - make installkernel
    - make -C libexec/atf/atf-pytest-wrapper -j$(sysctl -n hw.ncpu) all install
    - make -C tests/sys -j$(sysctl -n hw.ncpu) all install
    - make -C tests/atf_python -j$(sysctl -n hw.ncpu) all install
    - cp $CIRRUS_WORKING_DIR/tests/conftest.py /usr/tests
  test_netlink_script:
    - kyua test -k /usr/tests/Kyuafile sys/netlink/test_rtnl_route.py:TestRtNlRoute::test_add_route6_ll_if_gw
    - kyua test -k /usr/tests/Kyuafile sys/netlink/test_rtnl_route.py:TestRtNlRoute::test_add_route4_ll_if_gw
  always:
    test_netlink_report_script:
      - kyua report --results-file=/usr/tests --results-filter=failed --verbose
