freebsd_instance:
   image_family: freebsd-15-0-snap

task:
  make_script:
    - make -C usr.bin/grep -j$(sysctl -n hw.ncpu) all install
  test_grep_script:
    - kyua test -k /usr/tests/Kyuafile usr.bin/grep/
  always:
    test_grep_report_script:
      - kyua report --results-file=/usr/tests --results-filter=failed --verbose
