# $FreeBSD$

freebsd_instance:
  image_family: freebsd-14-0-snap

task:
  timeout_in: 120m
  setup_script:
    - pw useradd user
    - mkdir -p /usr/obj/$(pwd -P)
    - chown user:user /usr/obj/$(pwd -P)
    - sh .cirrus-ci/pkg-install.sh llvm15
  build_script:
    - su user -c "make -j$(sysctl -n hw.ncpu) CROSS_TOOLCHAIN=llvm15 WITHOUT_TOOLCHAIN=yes buildworld buildkernel"
    - make installkernel
  install_script:
    - cd tests/sys/netinet
    - make -j$(sysctl -n hw.ncpu)
    - make -j$(sysctl -n hw.ncpu) install
  in_mcast_test_script:
    - kyua test -k /usr/tests/Kyuafile sys/netinet/in_mcast_test
  always:
    in_mcast_test_report_script:
      - cd /usr/tests
      - kyua report --results-file=LATEST --results-filter=failed --verbose
