# $FreeBSD$

freebsd_instance:
   image_family: freebsd-14-0-snap

task:
  install_script:
    - make -C tests/sys/common -j$(sysctl -n hw.ncpu) all install
    - cp $CIRRUS_WORKING_DIR/usr.bin/tests/regress.m4 /usr/tests/usr.bin
  setup_script:
    - make -C usr.bin/xargs -j$(sysctl -n hw.ncpu) all install
  test_xargs_script:
    - kyua test -k /usr/tests/Kyuafile usr.bin/xargs/legacy_test:main
  always:
    test_xargs_report_script:
      - cd /usr/tests
      - kyua report --results-file=LATEST --results-filter=failed --verbose
