# $FreeBSD$

freebsd_instance:
  image_family: freebsd-14-0-snap

task:
  timeout_in: 120m
  install_script:
    - pkg install -y net/scapy textproc/igor
    - ls
    - cd sbin/ping
    - make -j$(sysctl -n hw.ncpu)
    - make -j$(sysctl -n hw.ncpu) install
  test_ping_script:
    - kyua test -k /usr/tests/Kyuafile sbin/ping/ping_test
 #lint_ping_man_page_script:
 #  - cd sbin/ping
 #  - mandoc -Tlint ping.8
 #  - igor ping.8
  always:
    test_ping_report_script:
      - cd /usr/tests
      - kyua report --results-file=LATEST --results-filter=failed --verbose
