freebsd_instance:
  image_family: freebsd-14-0-snap

task:
  timeout_in: 120m
  install_tests_script:
    - cd tests/sys/fs/tmpfs/
    - make -j$(sysctl -n hw.ncpu)
    - make -j$(sysctl -n hw.ncpu) install
  test_tmpfs_script:
    - kyua test -k /usr/tests/Kyuafile sys/fs/tmpfs/times_test
  always:
    test_tmpfs_report_script:
      - cd /usr/tests
      - kyua report --results-file=LATEST --results-filter=failed --verbose
