freebsd_instance:
   image_family: freebsd-15-0-snap

task:
  make_script:
    - make -C libexec/nuageinit -j$(sysctl -n hw.ncpu) all install
  test_nuageinit_script:
    - kyua test -k /usr/tests/Kyuafile libexec/nuageinit/
  always:
    test_nuageinit_report_script:
      - kyua report --results-file=/usr/tests --results-filter=failed --verbose
