# $FreeBSD$

freebsd_instance:
   image_family: freebsd-14-0-snap

task:
  install_script:
    - pkg delete -y python2
    - pkg autoremove -y
    - pkg update
    - pkg upgrade -y
    - pkg install -y devel/py-pytest net/scapy
    - make -C libexec/atf/atf-pytest-wrapper -j$(sysctl -n hw.ncpu) all install
    - make -C tests/sys/common -j$(sysctl -n hw.ncpu) all install
    - make -C tests/atf_python -j$(sysctl -n hw.ncpu) all install
    - cp $CIRRUS_WORKING_DIR/tests/conftest.py /usr/tests
  setup_script:
    - make -C lib/libifconfig -j$(sysctl -n hw.ncpu) all install
    - make -C sbin/ifconfig -j$(sysctl -n hw.ncpu) all install
  test_ifconfig_script:
    - kyua test -k /usr/tests/Kyuafile sbin/ifconfig/test_ifconfig.py
  always:
    test_ifconfig_report_script:
      - cd /usr/tests
      - kyua report --results-file=LATEST --results-filter=failed --verbose
