freebsd_instance:
  image_family: freebsd-15-0-snap

task:
  timeout_in: 120m
  install_script:
    - uname -a
    - pkg install -y net/scapy
    - cd $CIRRUS_WORKING_DIR/sbin/pfctl
    - make -j$(sysctl -n hw.ncpu)
    - make -j$(sysctl -n hw.ncpu) install
    - cd $CIRRUS_WORKING_DIR/tests/sys/netpfil/pf
    - make -j$(sysctl -n hw.ncpu)
    - make -j$(sysctl -n hw.ncpu) install
  test_anchor_script:
    - kyua test -k /usr/tests/Kyuafile sys/netpfil/pf/anchor
  always:
    test_anchor_report_script:
      - cd /usr/tests
      - kyua report --results-file=LATEST --results-filter=failed --verbose
