freebsd_instance:
   image_family: freebsd-15-0-snap

task:
  install_script:
    - pkg update
    - pkg upgrade -y
    - pkg autoremove -y
    - pkg install -y devel/py-pytest net/scapy
    - make -C libexec/atf/atf-pytest-wrapper -j$(sysctl -n hw.ncpu) all install
    - make -C tests/sys/common -j$(sysctl -n hw.ncpu) all install
    - make -C tests/atf_python -j$(sysctl -n hw.ncpu) all install
    - cp $CIRRUS_WORKING_DIR/tests/conftest.py /usr/tests
  setup_script:
    - make -C sbin/ping -j$(sysctl -n hw.ncpu) all install
  test_ping_script:
    - kyua test -k /usr/tests/Kyuafile sbin/ping/ping_test
    - kyua test -k /usr/tests/Kyuafile sbin/ping/test_ping.py
  always:
    test_ping_report_script:
      - cd /usr/tests
      - kyua report --results-file=LATEST --results-filter=failed --verbose
