freebsd_instance:
  image_family: freebsd-15-0-snap

task:
  timeout_in: 120m
  install_script:
    - uname -a
    - pkg install -y net/scapy
    - cd tests/sys/netinet6/frag6
    - make -j$(sysctl -n hw.ncpu)
    - make -j$(sysctl -n hw.ncpu) install
  test_frag6_script:
    - kyua test -k /usr/tests/Kyuafile sys/netinet6/frag6
  always:
    test_frag6_report_script:
      - cd /usr/tests
      - kyua report --results-file=LATEST --results-filter=failed --verbose
