# $FreeBSD$

freebsd_instance:
   image_family: freebsd-14-0-snap

task:
  matrix:
    - name: root
      env:
        TEST_USER: root
    - name: unprivileged
      env:
        TEST_USER: user
      add_user_script:
        - pw useradd user
        - mkdir /home/user
        - chown -R user:user /usr/home/user

  install_script:
    - pkg install -y devel/py-pytest net/scapy
    - make -C libexec/atf/atf-pytest-wrapper -j$(sysctl -n hw.ncpu) all install
    - make -C tests/sys/common -j$(sysctl -n hw.ncpu) all install
    - make -C tests/atf_python -j$(sysctl -n hw.ncpu) all install
    - cp $CIRRUS_WORKING_DIR/tests/conftest.py /usr/tests
  setup_script:
    - make -C tests/examples -j$(sysctl -n hw.ncpu) all install
  test_examples_script:
    - su -l $TEST_USER -c 'kyua test -k /usr/tests/Kyuafile examples/test_examples.py'
  always:
    test_examples_report_script:
      - su -l $TEST_USER -c 'cd /usr/tests ; kyua report --results-file=LATEST --results-filter=failed --verbose'
