# Common utility functions

require_ipsec()
{
	kldstat -q -n ipsec ||
	    if ! kldload ipsec 1>/dev/null 2>&1; then
		atf_skip "IPsec is not configured"
	    fi
}

require_ipv4()
{
	if ! getaddrinfo -f inet localhost 1>/dev/null 2>&1; then
		atf_skip "IPv4 is not configured"
	fi
}

require_ipv6()
{
	if ! getaddrinfo -f inet6 localhost 1>/dev/null 2>&1; then
		atf_skip "IPv6 is not configured"
	fi
}

# Common exit codes from sysexits(3)
EX_OK=0		# successful termination
EX__BASE=64	# base value for error messages
EX_USAGE=64	# command line usage error
EX_DATAERR=65	# data format error
EX_NOINPUT=66	# cannot open input
EX_NOUSER=67	# addressee unknown
EX_NOHOST=68	# host name unknown
EX_UNAVAILABLE=69	# service unavailable
EX_SOFTWARE=70	# internal software error
EX_OSERR=71	# system error (e.g., can't fork)
EX_OSFILE=72	# critical OS file missing
EX_CANTCREAT=73	# can't create (user) output file
EX_IOERR=74	# input/output error
EX_TEMPFAIL=75	# temp failure; user is invited to retry
EX_PROTOCOL=76	# remote error in protocol
EX_NOPERM=77	# permission denied
EX_CONFIG=78	# configuration error
EX__MAX=78	# maximum listed value
