# $FreeBSD$

icmp_control_messages()
{
	printf "%s\n" \
	    "3 0 Destination Net Unreachable" \
	    "3 1 Destination Host Unreachable" \
	    "3 2 Destination Protocol Unreachable" \
	    "3 3 Destination Port Unreachable" \
	    "3 4 frag needed and DF set" \
	    "3 5 Source Route Failed" \
	    "3 6 Destination Network Unknown" \
	    "3 7 Destination Host Unknown" \
	    "3 8 Source Host Isolated" \
	    "3 11 Network Unreachable for Type of Service" \
	    "3 12 Host Unreachable for Type of Service" \
	    "3 13 Communication prohibited by filter" \
	    "3 14 Host Precedence Violation" \
	    "3 15 Precedence Cutoff in Effect" \
	    "3 255 Dest Unreachable, Bad Code: 255" \
	    "4 0 Source Quench" \
	    "5 0 Redirect Network" \
	    "5 1 Redirect Host" \
	    "5 2 Redirect Type of Service and Network" \
	    "5 3 Redirect Type of Service and Host" \
	    "5 255 Redirect, Bad Code: 255" \
	    "9 0 Router Advertisement" \
	    "10 0 Router Solicitation" \
	    "11 0 Time to live exceeded" \
	    "11 1 Frag reassembly time exceeded" \
	    "11 255 Time exceeded, Bad Code: 255" \
	    "12 0 Parameter problem" \
	    "12 1 Missing a Required Option" \
	    "12 2 Bad Length" \
	    "12 255 Parameter Problem, Bad Code: 255" \
	    "14 0 Timestamp Reply" \
	    "15 0 Information Request" \
	    "16 0 Information Reply" \
	    "17 0 Address Mask Request" \
	    "18 0 Address Mask Reply" \
	    "255 255 Bad ICMP type: 255, Code: 255"
}
