#	$NetBSD: Makefile,v 1.2 2025/02/05 20:24:26 christos Exp $

SUBDIR=		rc.d

FILESDIR=	/usr/share/examples/blacklist
FILESMODE=	644
FILES=		blacklistd.conf ipf.conf npf.conf

.include <bsd.files.mk>
.include <bsd.subdir.mk>
