---
name: Quick Checker

on:
  push:
    branches: [ 'bsdimp-ci-*' ]
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          set-safe-directory: '/home/runner/work/freebsd/freebsd'
      - name: Check Email
        run:  sh ./tools/build/check-email.sh $GITHUB_BASE_REF..$GITHUB_HEAD_REF
      - name: Check Style
        run:  ./tools/build/checkstyle9.pl -color=always $GITHUB_BASE_REF..$GITHUB_HEAD_REF
